### ISSUE TITLE
Some Preset Layouts Unable to be Loaded

### ISSUE THREAD

**Issue by ghost** [stevep99/keyboard-layout-analyzer#1]
Several preset layouts are unable to be loaded. These include, but are not limited to: Arensito, Carpalx, Neo, MTGAP, Soul; Colemak-Split-Space; anything using a Matrix layout; Most - perhaps all - Ergodox layouts.
Upon trying to load such a layout this message appears:
> Unexpected Error. Layout not loaded.

Chrome: Version 83.0.4103.61 (Official Build) (64-bit)
Analyser version: 3.0.0 (according to package.json) 
![image](https://user-images.githubusercontent.com/65094911/83350675-05deaa80-a33e-11ea-919d-3fb582e7b8b5.png)

**Comment by stevep99** [comment]
I know this is from a while ago now, but are you still experiencing this? I can't reproduce currently with Chrome.

**Comment by ghost** [comment]
Yes, it is still the same.

**Comment by stevep99** [comment]
I haven't been able to reproduce it. Are you able to test on another computer with Chrome? I wonder if it's a caching issue, maybe force refresh/clear cache?

**Comment by ghost** [comment]
I am afraid the issue persists. Hopefully this can help: a screenshot of the console after attempting to load Ergo-Norman
![image](https://user-images.githubusercontent.com/65094911/90282282-5d38e500-de6e-11ea-9162-a712fd28e9e8.png)

**Comment by stevep99** [comment]
Ah, I have figured out what you are doing. You must have cloned the project are just viewing the pages on your machine. This won't work as the analyzer is only designed to run through a web server. 

You should run it by visiting https://stevep99.github.io/keyboard-layout-analyzer/

I have updated the README in the project to make this clearer.

**Comment by ghost** [comment]
It works great now, thank you! :)
